/**
 * Centralized Query Key Factory for TanStack Query.
 * Manages cache key lifecycles, consistency, and security across the application.
 */
export const queryKeys = {
  actor: (principalId?: string) => ['actor', principalId] as const,
  dashboardStats: () => ['dashboardStats'] as const,
  invoices: () => ['invoices'] as const,
  invoice: (id: string | number | bigint) => ['invoice', id.toString()] as const,
  nextInvoiceNumber: () => ['nextInvoiceNumber'] as const,
  settings: () => ['settings'] as const,
  userSelf: () => ['userSelf'] as const,
  users: () => ['users'] as const,
  activityLogs: () => ['activityLogs'] as const,
  products: () => ['products'] as const,
  customers: () => ['customers'] as const,
  payments: (customerId?: string) => customerId ? ['payments', customerId] as const : ['payments'] as const,
  rawMaterials: () => ['rawMaterials'] as const,
  purchases: () => ['purchases'] as const,
  vendors: () => ['vendors'] as const,
  purchaseOrders: () => ['purchaseOrders'] as const,
  grns: () => ['grns'] as const,
  expenses: () => ['expenses'] as const,
  vendorPayments: () => ['vendorPayments'] as const,
  materialConsumptions: () => ['materialConsumptions'] as const,
  employees: () => ['employees'] as const,
  jobWorkList: () => ['jobWorkList'] as const,
  employeePayments: () => ['employeePayments'] as const,
  employeeDashboardStats: () => ['employeeDashboardStats'] as const,
  customerOrderLinks: () => ['customerOrderLinks'] as const,
  karigarCollections: () => ['karigarCollections'] as const,
  stockMovements: () => ['stockMovements'] as const,
  auditLogs: () => ['auditLogs'] as const,
  employeeLedger: () => ['employeeLedger'] as const,
  permissions: () => ['permissions'] as const,
  salesOrders: () => ['salesOrders'] as const,
  productionRequirements: () => ['productionRequirements'] as const,
  purchaseRequirements: () => ['purchaseRequirements'] as const,
  mrpRecords: () => ['mrpRecords'] as const,
  purchaseInvoices: () => ['purchaseInvoices'] as const,
  purchaseInvoice: (id: string | number | bigint) => ['purchaseInvoice', id.toString()] as const,
  vendorOutstanding: () => ['vendorOutstanding'] as const,
  vendorLedger: () => ['vendorLedger'] as const,
  systemAuditLogs: () => ['systemAuditLogs'] as const,
  consumptionHistory: () => ['consumptionHistory'] as const,
  employeeDashboard: () => ['employeeDashboard'] as const,
  jobWorks: () => ['jobWorks'] as const,
  karigarLedger: (employeeName?: string) => employeeName ? ['karigarLedger', employeeName] as const : ['karigarLedger'] as const,
  collections: () => ['collections'] as const,
  stockReconciliation: () => ['stockReconciliation'] as const,
  consumptionLogs: () => ['consumptionLogs'] as const,
  finishedGoodsLogs: () => ['finishedGoodsLogs'] as const,
};
