/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Settings {
    businessInfo: BusinessInfo;
    termsAndConditions: string;
    defaultGstRate: number;
    allowStaffCollection: boolean;
    enableRejectedWage: boolean;
    companyLogo?: string;
    companyName?: string;
    themeColors?: string;
    sidebarStyle?: string;
    allowAdminBackupRestore?: boolean;
    enableAutoStockAlerts?: boolean;
    alertFrequency?: string;
    lowStockAlertThreshold?: number;
}
export type Time = bigint;
export type BusinessInfo = string;

export type Role = { Admin: null } | { Manager: null } | { Staff: null };

export type Department =
  | { Sales: null }
  | { Purchase: null }
  | { Inventory: null }
  | { Production: null }
  | { Finance: null }
  | { Staff: null }
  | { AdminSettings: null };

export interface Permissions {
    canView: boolean;
    canCreate: boolean;
    canEdit: boolean;
    canDelete: boolean;
    canApprove: boolean;
    canExport: boolean;
    canPrint: boolean;
    canManageStaff: boolean;
    canViewLogs: boolean;
    canBackupRestore: boolean;
    canAdjustStock: boolean;
    canAccessFinance: boolean;
    canAccessReports: boolean;
    "whatsapp.viewStatus"?: boolean;
    "whatsapp.sendInvoice"?: boolean;
    "whatsapp.resendInvoice"?: boolean;
    "whatsapp.viewLogs"?: boolean;
    "whatsapp.manageSettings"?: boolean;
    "whatsapp.manageAutomation"?: boolean;
}

export interface User {
    principalId: Principal;
    name: string;
    username: string;
    role: Role;
    createdAt: Time;
    email?: string;
    mobile?: string;
    address?: string;
    profilePhoto?: string;
    status?: string;
    lastLogin?: string;
    passwordHash?: string;
    needsPasswordChange?: boolean;
    department?: Department;
    permissions?: Permissions;
}

export interface ActivityLog {
    id: bigint;
    timestamp: Time;
    userPrincipal: string;
    userName: string;
    action: string;
    details: string;
    operator?: string;
    operatorRole?: string;
    module?: string;
    targetUser?: string;
    targetRole?: string;
}

export interface BOMRequirement {
    materialId: string;
    quantity: number;
    qtyPerUnit?: number;
    unitConfig?: {
        label: string;
        type: string;
        symbol: string;
        conversionToBase?: number | null;
    };
    legacyUnit?: string;
    qtyPerUnitBase?: number;
    schemaVersion?: number;
}
export interface ProductItem {
    id: string;
    vigat: string;
    rate: number;
    hsnCode: string;
    stock: bigint;
    productionCost: number;
    bom: Array<BOMRequirement>;
    photoUrl?: string;
    reservedStock?: bigint;
    availableToSell?: bigint;
}
export interface CustomerItem {
    id: string;
    name: string;
    businessAddress: string;
    phone: string;
    gstNo: string;
}
export interface Payment {
    id: bigint;
    customerId: string;
    invoiceNumber: string;
    amount: number;
    date: Time;
    notes: string;
}
export interface RawMaterial {
    id: string;
    name: string;
    category: string;
    openingStock: number;
    purchasedQty: number;
    consumedQty: number;
    currentStock: number;
    unitCost: number;
    unit: string;
    minStockAlert: number;
    photoUrl?: string;
    reorderLevel?: number;
    minimumStock?: number;
    preferredVendor?: string;
}

export interface SalesOrderItem {
    productId: string;
    productName: string;
    sku: string;
    qty: number;
    rate: number;
    amount: number;
    reservedQty: number;
    availableStock: number;
    needProductionQty: number;
}

export interface SalesOrder {
    id: string;
    orderNo: string;
    customerId: string;
    customerName: string;
    orderDate: string;
    deliveryDate: string;
    items: SalesOrderItem[];
    subtotal: number;
    gst: number;
    grandTotal: number;
    paymentStatus: string;
    status: string;
    createdBy: string;
    createdAt: string;
    updatedBy: string;
    updatedAt: string;
}

export interface StockReservation {
    id: string;
    salesOrderId: string;
    productId: string;
    productName: string;
    reservedQty: number;
    createdAt: string;
}

export interface ProductionRequirement {
    id: string;
    salesOrderId: string;
    productId: string;
    productName: string;
    requiredQty: number;
    plannedQty: number;
    completedQty: number;
    status: string;
    priority: string;
    expectedDate: string;
    createdAt: string;
}

export interface MRPMaterialRequirement {
    materialId: string;
    materialName: string;
    requiredQty: number;
    availableQty: number;
    shortageQty: number;
}

export interface MRPRecord {
    id: string;
    productionRequirementId: string;
    productId: string;
    productName: string;
    requiredMaterials: MRPMaterialRequirement[];
    status: string;
    createdAt: string;
}

export interface PurchaseRequirement {
    id: string;
    mrpId: string;
    materialId: string;
    materialName: string;
    requiredQty: number;
    availableQty: number;
    shortageQty: number;
    vendorId: string;
    status: string;
    createdAt: string;
}

export interface PurchaseItem {
    materialId: string;
    quantity: number;
    unit: string;
    rate: number;
    gstPercent: number;
    amount: number;
}
export interface Purchase {
    id: bigint;
    purchaseNumber: string;
    date: Time;
    vendorName: string;
    vendorMobile: string;
    vendorGstNumber: string;
    vendorAddress: string;
    items: Array<PurchaseItem>;
    totalAmount: number;
    paidAmount: number;
}
export interface Expense {
    id: bigint;
    date: Time;
    category: string;
    amount: number;
    description: string;
}
export interface VendorPayment {
    id: bigint;
    vendorName: string;
    purchaseNumber: string;
    amount: number;
    date: Time;
    notes: string;
}
export interface MaterialConsumptionEntry {
    id: bigint;
    date: Time;
    finishedGoodId: string;
    finishedGoodName: string;
    invoiceNumber: string;
    materialId: string;
    materialName: string;
    quantityConsumed: number;
}
export interface Invoice {
    id: bigint;
    customerInfo: CustomerInfo;
    date: Time;
    businessInfo: BusinessInfo;
    invoiceNumber: string;
    totalAmount: number;
    paidAmount: number;
    products: Array<Product>;
    creatorPrincipal: string;
    creatorName: string;
    previousBalanceAtCreation?: number;
    advanceBalanceAtCreation?: number;
    currentInvoiceTotalAtCreation?: number;
    totalPayableAtCreation?: number;
    paidAmountAtCreation?: number;
    finalDueAtCreation?: number;
}
export interface CustomerInfo {
    taxId: string;
    name: string;
    businessAddress: string;
}
export interface DashboardStats {
    allTimeTotalSales: number;
    todayTotalSales: number;
    todayInvoiceCount: bigint;
    allTimeInvoiceCount: bigint;
    totalOutstandingAmount: number;
    customersWithOutstanding: bigint;
    overdueInvoiceCount: bigint;
    todayCollections: number;
    totalPurchases: number;
    totalProfit: number;
    totalGst: number;
    vendorDue: number;
    stockValue: number;
}
export type Product = [string, bigint, bigint];

export interface CustomerOrderLink {
    customerName: string;
    orderNumber: string;
}
export interface Employee {
    id: string;
    name: string;
    mobile: string;
    address: string;
    joiningDate: Time;
    skillType: string;
    status: string;
}
export interface JobWork {
    id: bigint;
    jobDate: Time;
    employeeName: string;
    mobileNumber: string;
    workType: string;
    productName: string;
    productCode: string;
    hsnCode: string;
    qtyGiven: number;
    qtyAssigned: number;
    ratePerPiece: number;
    expectedReturnDate: Time;
    expectedCompletionDate: Time;
    status: string;
    remarks: string;
    collectedQty: number;
    completedQty: number;
    rejectedQty: number;
    acceptedQty: number;
    customerOrderLink: CustomerOrderLink | null;
    lastUpdated?: Time;
    totalCollectedQty?: number;
    totalRejectedQty?: number;
    totalAcceptedQty?: number;
    createdByUserId?: string | null;
    createdByUsername?: string | null;
    createdByFullName?: string | null;
    createdByRole?: string | null;
    updatedByUserId?: string | null;
    updatedByUsername?: string | null;
    updatedByFullName?: string | null;
    updatedByRole?: string | null;
    lastAction?: string | null;
}
export interface DailyWorkUpdate {
    id: bigint;
    date: Time;
    jobId: bigint;
    completedQty: number;
    remarks: string;
}
export interface JobCollection {
    id: bigint;
    collectionDate: Time;
    jobId: bigint;
    collectedQty: number;
    rejectedQty: number;
    acceptedQty: number;
}
export interface KarigarCollection {
    id: bigint;
    collectionDate: Time;
    jobWorkNo: bigint;
    karigarName: string;
    productName: string;
    qtyGiven: number;
    prevCollectedQty: number;
    pendingQty: number;
    todayCollectedQty: number;
    rejectedQty: number;
    acceptedQty: number;
    remarks: string;
    createdBy?: string;
    createdById?: string;
    createdAt?: string;
    inspectedBy?: string;
    inspectedById?: string;
    inspectedAt?: string;
}
export interface StockMovement {
    id: bigint;
    date: Time;
    productName: string;
    movementType: string;
    qtyAdded: number;
    relatedJobWorkNo: bigint;
    relatedCollectionNo: bigint;
    userName: string;
}
export interface AuditLog {
    id: bigint;
    timestamp: Time;
    user: string;
    action: string;
    description: string;
    jobWorkNo?: string;
    collectionNo?: string;
    product?: string;
    employee?: string;
    details?: string;
}
export interface EmployeeLedgerEntry {
    id: bigint;
    employeeName: string;
    jobWorkNo: bigint;
    date: Time;
    productName: string;
    qtyGiven: number;
    acceptedQty: number;
    rejectedQty: number;
    pendingQty: number;
    rate: number;
    totalWage: number;
    paidAmount: number;
    balanceAmount: number;
    status: string;
    collectionId?: string;
    jobWorkId?: string;
    employeeId?: string;
    source?: string;
    reversed?: boolean;
}
export interface EmployeePayment {
    id: bigint;
    paymentDate: Time;
    employeeName: string;
    amountPaid: number;
    paymentMode: string;
    remarks: string;
}
export interface EmployeeDashboardStats {
    totalEmployees: bigint;
    activeJobs: bigint;
    completedJobs?: bigint;
    pendingJobs?: bigint;
    pendingQuantity: number;
    todayCollectedQty: number;
    totalRejectedQty: number;
    wagesDue: number;
    stockValue: number;
    todayProduction?: number;
}

export interface DatabaseBackup {
    invoices: Array<Invoice>;
    lastInvoiceId: bigint;
    settings: Settings | null;
    users: Array<User>;
    userCount: bigint;
    activityLogs: Array<ActivityLog>;
    lastLogId: bigint;
    productsList: Array<ProductItem>;
    productCount: bigint;
    customersList: Array<CustomerItem>;
    customerCount: bigint;
    paymentsList: Array<Payment>;
    lastPaymentId: bigint;
    rawMaterialsList: Array<RawMaterial>;
    purchasesList: Array<Purchase>;
    expensesList: Array<Expense>;
    vendorPaymentsList: Array<VendorPayment>;
    consumptionHistory: Array<MaterialConsumptionEntry>;
    lastPurchaseId: bigint;
    lastExpenseId: bigint;
    lastVendorPaymentId: bigint;
    lastConsumptionId: bigint;
    employeesList: Array<Employee>;
    jobWorksList: Array<JobWork>;
    dailyWorkUpdatesList: Array<DailyWorkUpdate>;
    jobCollectionsList: Array<JobCollection>;
    employeePaymentsList: Array<EmployeePayment>;
    collectionsList: Array<KarigarCollection>;
    stockMovementsList: Array<StockMovement>;
    auditLogsList: Array<AuditLog>;
    employeeLedgersList: Array<EmployeeLedgerEntry>;
    consumptionLogsList: Array<ConsumptionLog>;
    lastConsumptionLogId: bigint;
    finishedGoodsLogsList: Array<FinishedGoodsLog>;
    lastFinishedGoodsLogId: bigint;
    employeeCount: bigint;
    lastJobWorkId: bigint;
    lastDailyWorkUpdateId: bigint;
    lastJobCollectionId: bigint;
    lastEmployeePaymentId: bigint;
    lastCollectionId: bigint;
    lastStockMovementId: bigint;
    lastAuditLogId: bigint;
    lastEmployeeLedgerId: bigint;
}

export interface PurchaseOrder {
    id: string;
    poNumber: string;
    mrpId?: string;
    materialId: string;
    materialName: string;
    requiredQty: number;
    orderedQty: number;
    unit: string;
    rate: number;
    gstPercent: number;
    totalAmount: number;
    vendorId: string;
    status: "Draft" | "Sent" | "Approved" | "Partial" | "Completed" | "Cancelled";
    createdAt: string;
    approvedAt?: string;
    approvedBy?: string;
    purchaseRequirementId?: string;
    receiptHistory?: Array<{
        receiptId: string;
        grnNo: string;
        invoiceNo: string;
        qty: number;
        receivedDate: string;
        receivedBy: string;
    }>;
}

export interface GRN {
    grnNo: string;
    poNumber: string;
    invoiceNo?: string;
    receivedDate: string;
    vendorId: string;
    receivedBy: string;
    items: Array<{
        materialId: string;
        materialName: string;
        quantity: number;
        unit: string;
        batchNo?: string;
        expiryDate?: string;
    }>;
    status: "Received" | "Inspected" | "Returned";
    remarks?: string;
}

export interface backendInterface {
    deleteInvoice(id: bigint): Promise<void>;
    getDashboardStats(): Promise<DashboardStats>;
    getInvoiceById(id: bigint): Promise<Invoice>;
    getNextInvoiceNumber(): Promise<string>;
    getInvoices(): Promise<Array<Invoice>>;
    getSettings(): Promise<Settings>;
    saveInvoice(businessInfo: BusinessInfo, customerInfo: CustomerInfo, products: Array<Product>, totalAmount: number, paidAmount: number): Promise<string>;
    saveSettings(businessInfo: BusinessInfo, defaultGstRate: number, termsAndConditions: string, allowStaffCollection?: boolean, enableRejectedWage?: boolean, companyLogo?: string, companyName?: string, themeColors?: string, sidebarStyle?: string, allowAdminBackupRestore?: boolean, enableAutoStockAlerts?: boolean, alertFrequency?: string, lowStockAlertThreshold?: number): Promise<void>;
    updateInvoice(id: bigint, businessInfo: BusinessInfo, customerInfo: CustomerInfo, products: Array<Product>, totalAmount: number, paidAmount: number): Promise<void>;
    registerOrGetSelf(): Promise<User | null>;
    createUser(principalText: string, name: string, username: string, roleText: string, email?: string, mobile?: string, address?: string, profilePhoto?: string, status?: string, passwordHash?: string, departmentText?: string, permissionsObj?: Permissions): Promise<string>;
    editUser(principalText: string, name: string, username: string, email: string, mobile: string, roleText: string, status: string, departmentText?: string, permissionsObj?: Permissions): Promise<void>;
    deleteUser(principalText: string): Promise<void>;
    getUsers(): Promise<Array<User>>;
    getActivityLogs(): Promise<Array<ActivityLog>>;
    logUserAction(action: string, details: string): Promise<void>;
    updateProfile(email: string, name: string, mobile: string, address: string, profilePhoto: string): Promise<void>;
    changePassword(newPassword: string, newPrincipalId: string): Promise<void>;
    toggleUserStatus(principalText: string, status: string): Promise<void>;
    adminResetPassword(principalText: string, newPrincipalId: string, newPasswordHash?: string): Promise<void>;
    getProducts(): Promise<Array<ProductItem>>;
    saveProduct(id: string, vigat: string, rate: number, hsnCode: string, stock: bigint, productionCost: number, bom: Array<BOMRequirement>): Promise<void>;
    deleteProduct(id: string): Promise<void>;
    getCustomers(): Promise<Array<CustomerItem>>;
    saveCustomer(id: string, name: string, businessAddress: string, phone: string, gstNo: string): Promise<void>;

    updateInvoice(id: bigint, businessInfo: BusinessInfo, customerInfo: CustomerInfo, products: Array<Product>, totalAmount: number, paidAmount: number): Promise<void>;
    registerOrGetSelf(): Promise<User | null>;
    createUser(principalText: string, name: string, username: string, roleText: string, email?: string, mobile?: string, address?: string, profilePhoto?: string, status?: string, passwordHash?: string, departmentText?: string, permissionsObj?: Permissions): Promise<string>;
    editUser(principalText: string, name: string, username: string, email: string, mobile: string, roleText: string, status: string, departmentText?: string, permissionsObj?: Permissions): Promise<void>;
    deleteUser(principalText: string): Promise<void>;
    getUsers(): Promise<Array<User>>;
    getActivityLogs(): Promise<Array<ActivityLog>>;
    logUserAction(action: string, details: string): Promise<void>;
    updateProfile(email: string, name: string, mobile: string, address: string, profilePhoto: string): Promise<void>;
    changePassword(newPassword: string, newPrincipalId: string): Promise<void>;
    toggleUserStatus(principalText: string, status: string): Promise<void>;
    adminResetPassword(principalText: string, newPrincipalId: string, newPasswordHash?: string): Promise<void>;
    getProducts(): Promise<Array<ProductItem>>;
    saveProduct(id: string, vigat: string, rate: number, hsnCode: string, stock: bigint, productionCost: number, bom: Array<BOMRequirement>): Promise<void>;
    deleteProduct(id: string): Promise<void>;
    getCustomers(): Promise<Array<CustomerItem>>;
    saveCustomer(id: string, name: string, businessAddress: string, phone: string, gstNo: string): Promise<void>;
    deleteCustomer(id: string): Promise<void>;
    collectPayment(customerId: string, amount: number, notes: string): Promise<void>;
    getPayments(): Promise<Array<Payment>>;
    getPaymentsByCustomer(customerId: string): Promise<Array<Payment>>;
    getRawMaterials(): Promise<Array<RawMaterial>>;
    saveRawMaterial(id: string, name: string, category: string, openingStock: number, unitCost: number, unit: string, minStock: number, reorderLevel?: number, minimumStock?: number, preferredVendor?: string): Promise<void>;
    deleteRawMaterial(id: string): Promise<void>;
    getPurchases(): Promise<Array<Purchase>>;
    savePurchase(purchaseNumber: string, vendorName: string, vendorMobile: string, vendorGstNumber: string, vendorAddress: string, items: Array<PurchaseItem>, totalAmount: number, paidAmount: number): Promise<string>;
    deletePurchase(id: bigint): Promise<void>;
    saveExpense(category: string, amount: number, description: string): Promise<bigint>;
    getExpenses(): Promise<Array<Expense>>;
    deleteExpense(id: bigint): Promise<void>;
    collectVendorPayment(vendorName: string, amount: number, notes: string): Promise<void>;
    getVendorPayments(): Promise<Array<VendorPayment>>;
    getMaterialConsumptionHistory(): Promise<Array<MaterialConsumptionEntry>>;

    getEmployees(): Promise<Array<Employee>>;
    saveEmployee(id: string, name: string, mobile: string, address: string, joiningDate: Time, skillType: string, status: string): Promise<string>;
    deleteEmployee(id: string): Promise<void>;
    getJobWorks(): Promise<Array<JobWork>>;
    saveJobWork(jobDate: Time, employeeName: string, mobileNumber: string, productName: string, productCode: string, hsnCode: string, qtyGiven: number, ratePerPiece: number, expectedReturnDate: Time, remarks: string, customerOrderLink: CustomerOrderLink | null): Promise<bigint>;
    updateJobWorkProgress(jobId: bigint, completedQty: number, remarks: string): Promise<void>;
    saveCollectionEntry(jobWorkNo: bigint, todayCollectedQty: number, rejectedQty: number, remarks: string): Promise<bigint>;
    editCollectionEntry(collectionId: bigint, todayCollectedQty: number, rejectedQty: number, remarks: string): Promise<void>;
    deleteCollectionEntry(collectionId: bigint): Promise<void>;
    getCollections(): Promise<Array<KarigarCollection>>;
    getStockMovementHistory(): Promise<Array<StockMovement>>;
    getSystemAuditLogs(): Promise<Array<AuditLog>>;
    getKarigarLedger(employeeName: string): Promise<Array<EmployeeLedgerEntry>>;
    getEmployeePayments(): Promise<Array<EmployeePayment>>;
    saveEmployeePayment(karigarName: string, paymentAmount: number, paymentMode: string, note: string): Promise<bigint>;
    editEmployeePayment(paymentId: bigint, paymentAmount: number, paymentMode: string, note: string): Promise<void>;
    deleteEmployeePayment(paymentId: bigint): Promise<void>;
    getEmployeeDashboardStats(): Promise<EmployeeDashboardStats>;
    getConsumptionLogs(): Promise<Array<ConsumptionLog>>;
    saveConsumptionLog(productName: string, batchNo: string, rawMaterialName: string, quantityUsed: number, unit: string, cost: number, employee: string, jobWorkNo: string, remarks: string): Promise<bigint>;
    getFinishedGoodsLogs(): Promise<Array<FinishedGoodsLog>>;
    saveFinishedGoodsLog(productName: string, quantity: number, logType: string, reason: string): Promise<bigint>;
    resetPasswordWithVerification(username: string, email: string, mobile: string, newPasswordHash: string, newPrincipalId: string): Promise<{ success: boolean; message: string }>;
    verifyMasterAdminIntegrity(): Promise<{ isValid: boolean; message: string }>;
    checkStockReconciliation(): Promise<Array<any>>;
    recalculateProductionReports(): Promise<void>;
    exportDatabase(): Promise<DatabaseBackup>;
    importDatabase(backup: DatabaseBackup): Promise<void>;
    sendWhatsAppInvoice(invoiceId: bigint, isResend: boolean): Promise<{ success: boolean; message: string }>;
    getWhatsAppLogs(): Promise<Array<any>>;
    getWhatsAppStatusForInvoice(invoiceId: bigint): Promise<{ sent: boolean; sentCount: number; lastSent?: number }>;
    getWhatsAppSettings(): Promise<any>;
    saveWhatsAppSettings(phoneNumberId: string, accessToken: string, templateName: string, automationEnabled: boolean): Promise<void>;
    runConsistencyAuditAndRepair(): Promise<Array<string>>;
    getStockAlerts(): Promise<Array<any>>;
    resolveStockAlert(id: string): Promise<void>;
    logWhatsAppStockAlertOpened(productId: string, productName: string, shortageQty: number, phoneNumberMasked?: string, source?: string): Promise<void>;
    getSalesOrders(): Promise<Array<SalesOrder>>;
    saveSalesOrder(order: SalesOrder): Promise<void>;
    deleteSalesOrder(id: string): Promise<void>;
    getProductionRequirements(): Promise<Array<ProductionRequirement>>;
    saveProductionRequirement(req: ProductionRequirement): Promise<void>;
    deleteProductionRequirement(id: string): Promise<void>;
    getPurchaseRequirements(): Promise<Array<PurchaseRequirement>>;
    savePurchaseRequirement(req: PurchaseRequirement): Promise<void>;
    deletePurchaseRequirement(id: string): Promise<void>;
    getMRPRecords(): Promise<Array<MRPRecord>>;
    saveMRPRecord(record: MRPRecord): Promise<void>;
    runMRP(requirementId: string): Promise<MRPRecord>;
    reserveStockForOrder(orderId: string): Promise<void>;
    completeProductionPlan(requirementId: string, completedQty: number): Promise<void>;
    receivePurchaseRequirement(requirementId: string, qty: number): Promise<void>;
    getPurchaseOrders(): Promise<Array<PurchaseOrder>>;
    savePurchaseOrder(po: PurchaseOrder): Promise<void>;
    deletePurchaseOrder(id: string): Promise<void>;
    getGRNs(): Promise<Array<GRN>>;
    saveGRN(grn: GRN): Promise<void>;
    receivePOItem(poId: string, qty: number, invoiceNo: string, expiryDate?: string, remarks?: string): Promise<void>;
    getPurchaseInvoices(): Promise<Array<any>>;
    getPurchaseInvoiceById(id: string): Promise<any>;
    recordPurchasePayment(invoiceId: string, paymentData: any): Promise<void>;
    cancelPurchaseInvoice(invoiceId: string): Promise<void>;
    normalizePurchaseInvoice(invoice: any): any;
    migrateLegacyPurchaseInvoices(): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async deleteInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getInvoiceById(arg0: bigint): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoiceById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoiceById(arg0);
            return result;
        }
    }
    async getNextInvoiceNumber(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextInvoiceNumber();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextInvoiceNumber();
            return result;
        }
    }
    async getInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoices();
            return result;
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async saveInvoice(arg0: BusinessInfo, arg1: CustomerInfo, arg2: Array<Product>, arg3: number, arg4: number): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveInvoice(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveInvoice(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveSettings(arg0: BusinessInfo, arg1: number, arg2: string, arg3?: boolean, arg4?: boolean, arg5?: string, arg6?: string, arg7?: string, arg8?: string, arg9?: boolean, arg10?: boolean, arg11?: string, arg12?: number): Promise<void> {
        const a3 = arg3 !== undefined ? arg3 : true;
        const a4 = arg4 !== undefined ? arg4 : false;
        const a5 = arg5 !== undefined ? [arg5] : [];
        const a6 = arg6 !== undefined ? [arg6] : [];
        const a7 = arg7 !== undefined ? [arg7] : [];
        const a8 = arg8 !== undefined ? [arg8] : [];
        const a9 = arg9 !== undefined ? [arg9] : [];
        const a10 = arg10 !== undefined ? [arg10] : [];
        const a11 = arg11 !== undefined ? [arg11] : [];
        const a12 = arg12 !== undefined ? [arg12] : [];
        if (this.processError) {
            try {
                const result = await this.actor.saveSettings(arg0, arg1, arg2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSettings(arg0, arg1, arg2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12);
            return result;
        }
    }
    async updateInvoice(arg0: bigint, arg1: BusinessInfo, arg2: CustomerInfo, arg3: Array<Product>, arg4: number, arg5: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async registerOrGetSelf(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOrGetSelf();
                return result.length > 0 ? result[0] : null;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOrGetSelf();
            return result.length > 0 ? result[0] : null;
        }
    }
    async createUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4?: string, arg5?: string, arg6?: string, arg7?: string, arg8?: string, arg9?: string, arg10?: string, arg11?: Permissions): Promise<string> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).createUser(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 || "", arg11 ? [arg11] : []);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).createUser(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 || "", arg11 ? [arg11] : []);
            return result;
        }
    }
    async editUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7?: string, arg8?: Permissions): Promise<void> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).editUser(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 || "", arg8 ? [arg8] : []);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).editUser(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 || "", arg8 ? [arg8] : []);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async changePassword(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changePassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePassword(arg0, arg1);
            return result;
        }
    }
    async toggleUserStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleUserStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleUserStatus(arg0, arg1);
            return result;
        }
    }
    async adminResetPassword(arg0: string, arg1: string, arg2?: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetPassword(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetPassword(arg0, arg1, arg2);
            return result;
        }
    }
    async logUserAction(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logUserAction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logUserAction(arg0, arg1);
            return result;
        }
    }
    async deleteUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return result;
        }
    }
    async getActivityLogs(): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLogs();
            return result;
        }
    }
    async getProducts(): Promise<Array<ProductItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async saveProduct(arg0: string, arg1: string, arg2: number, arg3: string, arg4: bigint, arg5: number, arg6: Array<BOMRequirement>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getCustomers(): Promise<Array<CustomerItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return result;
        }
    }
    async saveCustomer(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCustomer(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCustomer(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteCustomer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async collectPayment(arg0: string, arg1: number, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.collectPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.collectPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async getPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayments();
            return result;
        }
    }
    async getPaymentsByCustomer(arg0: string): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByCustomer(arg0);
            return result;
        }
    }
    async getRawMaterials(): Promise<Array<RawMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRawMaterials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRawMaterials();
            return result;
        }
    }
    async saveRawMaterial(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: string, arg6: number, arg7?: number, arg8?: number, arg9?: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveRawMaterial(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveRawMaterial(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteRawMaterial(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRawMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRawMaterial(arg0);
            return result;
        }
    }
    async getPurchases(): Promise<Array<Purchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchases();
            return result;
        }
    }
    async savePurchase(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<PurchaseItem>, arg6: number, arg7: number): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.savePurchase(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePurchase(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async deletePurchase(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePurchase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePurchase(arg0);
            return result;
        }
    }
    async saveExpense(arg0: string, arg1: number, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveExpense(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveExpense(arg0, arg1, arg2);
            return result;
        }
    }
    async getExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async collectVendorPayment(arg0: string, arg1: number, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.collectVendorPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.collectVendorPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async getVendorPayments(): Promise<Array<VendorPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorPayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorPayments();
            return result;
        }
    }
    async getMaterialConsumptionHistory(): Promise<Array<MaterialConsumptionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterialConsumptionHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterialConsumptionHistory();
            return result;
        }
    }
    async getEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployees();
            return result;
        }
    }
    async saveEmployee(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time, arg5: string, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEmployee(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEmployee(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteEmployee(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async getJobWorks(): Promise<Array<JobWork>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobWorks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobWorks();
            return result;
        }
    }
    async saveJobWork(
        arg0: Time,
        arg1: string,
        arg2: string,
        arg3: string,
        arg4: string,
        arg5: string,
        arg6: number,
        arg7: number,
        arg8: Time,
        arg9: string,
        arg10: CustomerOrderLink | null
    ): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveJobWork(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg10 ? [arg10] : []);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveJobWork(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 ? [arg10] : []);
            return result;
        }
    }
    async updateJobWorkProgress(arg0: bigint, arg1: number, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobWorkProgress(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobWorkProgress(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCollectionEntry(arg0: bigint, arg1: number, arg2: number, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCollectionEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCollectionEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async editCollectionEntry(arg0: bigint, arg1: number, arg2: number, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editCollectionEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editCollectionEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteCollectionEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCollectionEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCollectionEntry(arg0);
            return result;
        }
    }
    async getCollections(): Promise<Array<KarigarCollection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollections();
            return result;
        }
    }
    async getStockMovementHistory(): Promise<Array<StockMovement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockMovementHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockMovementHistory();
            return result;
        }
    }
    async getSystemAuditLogs(): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemAuditLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemAuditLogs();
            return result;
        }
    }
    async getKarigarLedger(arg0: string): Promise<Array<EmployeeLedgerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKarigarLedger(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKarigarLedger(arg0);
            return result;
        }
    }
    async getEmployeePayments(): Promise<Array<EmployeePayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeePayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeePayments();
            return result;
        }
    }
    async saveEmployeePayment(arg0: string, arg1: number, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEmployeePayment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEmployeePayment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async editEmployeePayment(arg0: bigint, arg1: number, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).editEmployeePayment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).editEmployeePayment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteEmployeePayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).deleteEmployeePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).deleteEmployeePayment(arg0);
            return result;
        }
    }
    async checkStockReconciliation(): Promise<Array<any>> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).checkStockReconciliation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).checkStockReconciliation();
            return result;
        }
    }
    async recalculateProductionReports(): Promise<void> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).recalculateProductionReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).recalculateProductionReports();
            return result;
        }
    }
    async getEmployeeDashboardStats(): Promise<EmployeeDashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeDashboardStats();
            return result;
        }
    }
    async getConsumptionLogs(): Promise<Array<ConsumptionLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConsumptionLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConsumptionLogs();
            return result;
        }
    }
    async saveConsumptionLog(arg0: string, arg1: string, arg2: string, arg3: number, arg4: string, arg5: number, arg6: string, arg7: string, arg8: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveConsumptionLog(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveConsumptionLog(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async getFinishedGoodsLogs(): Promise<Array<FinishedGoodsLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinishedGoodsLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinishedGoodsLogs();
            return result;
        }
    }
    async saveFinishedGoodsLog(arg0: string, arg1: number, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFinishedGoodsLog(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFinishedGoodsLog(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async verifyMasterAdminIntegrity(): Promise<{ isValid: boolean; message: string }> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).verifyMasterAdminIntegrity();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).verifyMasterAdminIntegrity();
            return result;
        }
    }
    async resetPasswordWithVerification(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<{ success: boolean; message: string }> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).resetPasswordWithVerification(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).resetPasswordWithVerification(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async exportDatabase(): Promise<DatabaseBackup> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).exportDatabase();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).exportDatabase();
            return result;
        }
    }
    async importDatabase(arg0: DatabaseBackup): Promise<void> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).importDatabase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).importDatabase(arg0);
            return result;
        }
    }
    async sendWhatsAppInvoice(arg0: bigint, arg1: boolean): Promise<{ success: boolean; message: string }> {
        if (this.processError) {
            try {
                return await (this.actor as any).sendWhatsAppInvoice(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).sendWhatsAppInvoice(arg0, arg1);
        }
    }
    async getWhatsAppLogs(): Promise<Array<any>> {
        if (this.processError) {
            try {
                return await (this.actor as any).getWhatsAppLogs();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).getWhatsAppLogs();
        }
    }
    async getWhatsAppStatusForInvoice(arg0: bigint): Promise<{ sent: boolean; sentCount: number; lastSent?: number }> {
        if (this.processError) {
            try {
                return await (this.actor as any).getWhatsAppStatusForInvoice(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).getWhatsAppStatusForInvoice(arg0);
        }
    }
    async getWhatsAppSettings(): Promise<any> {
        if (this.processError) {
            try {
                return await (this.actor as any).getWhatsAppSettings();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).getWhatsAppSettings();
        }
    }
    async saveWhatsAppSettings(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                return await (this.actor as any).saveWhatsAppSettings(arg0, arg1, arg2, arg3);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).saveWhatsAppSettings(arg0, arg1, arg2, arg3);
        }
    }
    async runConsistencyAuditAndRepair(): Promise<Array<string>> {
        if (this.processError) {
            try {
                return await (this.actor as any).runConsistencyAuditAndRepair();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await (this.actor as any).runConsistencyAuditAndRepair();
        }
    }
    async getStockAlerts(): Promise<Array<any>> {
        if ((this.actor as any).getStockAlerts) {
            return await (this.actor as any).getStockAlerts();
        }
        return [];
    }
    async resolveStockAlert(arg0: string): Promise<void> {
        if ((this.actor as any).resolveStockAlert) {
            await (this.actor as any).resolveStockAlert(arg0);
        }
    }
    async logWhatsAppStockAlertOpened(arg0: string, arg1: string, arg2: number, arg3?: string, arg4?: string): Promise<void> {
        if ((this.actor as any).logWhatsAppStockAlertOpened) {
            await (this.actor as any).logWhatsAppStockAlertOpened(arg0, arg1, arg2, arg3, arg4);
        }
    }
    async getSalesOrders(): Promise<Array<SalesOrder>> {
        if ((this.actor as any).getSalesOrders) {
            return await (this.actor as any).getSalesOrders();
        }
        return [];
    }
    async saveSalesOrder(order: SalesOrder): Promise<void> {
        if ((this.actor as any).saveSalesOrder) {
            await (this.actor as any).saveSalesOrder(order);
        }
    }
    async deleteSalesOrder(id: string): Promise<void> {
        if ((this.actor as any).deleteSalesOrder) {
            await (this.actor as any).deleteSalesOrder(id);
        }
    }
    async getProductionRequirements(): Promise<Array<ProductionRequirement>> {
        if ((this.actor as any).getProductionRequirements) {
            return await (this.actor as any).getProductionRequirements();
        }
        return [];
    }
    async saveProductionRequirement(req: ProductionRequirement): Promise<void> {
        if ((this.actor as any).saveProductionRequirement) {
            await (this.actor as any).saveProductionRequirement(req);
        }
    }
    async deleteProductionRequirement(id: string): Promise<void> {
        if ((this.actor as any).deleteProductionRequirement) {
            await (this.actor as any).deleteProductionRequirement(id);
        }
    }
    async getPurchaseRequirements(): Promise<Array<PurchaseRequirement>> {
        if ((this.actor as any).getPurchaseRequirements) {
            return await (this.actor as any).getPurchaseRequirements();
        }
        return [];
    }
    async savePurchaseRequirement(req: PurchaseRequirement): Promise<void> {
        if ((this.actor as any).savePurchaseRequirement) {
            await (this.actor as any).savePurchaseRequirement(req);
        }
    }
    async deletePurchaseRequirement(id: string): Promise<void> {
        if ((this.actor as any).deletePurchaseRequirement) {
            await (this.actor as any).deletePurchaseRequirement(id);
        }
    }
    async getMRPRecords(): Promise<Array<MRPRecord>> {
        if ((this.actor as any).getMRPRecords) {
            return await (this.actor as any).getMRPRecords();
        }
        return [];
    }
    async saveMRPRecord(record: MRPRecord): Promise<void> {
        if ((this.actor as any).saveMRPRecord) {
            await (this.actor as any).saveMRPRecord(record);
        }
    }
    async runMRP(requirementId: string): Promise<MRPRecord> {
        if ((this.actor as any).runMRP) {
            return await (this.actor as any).runMRP(requirementId);
        }
        throw new Error("runMRP not implemented on actor");
    }
    async reserveStockForOrder(orderId: string): Promise<void> {
        if ((this.actor as any).reserveStockForOrder) {
            await (this.actor as any).reserveStockForOrder(orderId);
        }
    }
    async completeProductionPlan(requirementId: string, completedQty: number): Promise<void> {
        if ((this.actor as any).completeProductionPlan) {
            await (this.actor as any).completeProductionPlan(requirementId, completedQty);
        }
    }
    async receivePurchaseRequirement(requirementId: string, qty: number): Promise<void> {
        if ((this.actor as any).receivePurchaseRequirement) {
            await (this.actor as any).receivePurchaseRequirement(requirementId, qty);
        }
    }
    async getPurchaseOrders(): Promise<Array<PurchaseOrder>> {
        if ((this.actor as any).getPurchaseOrders) {
            return await (this.actor as any).getPurchaseOrders();
        }
        return [];
    }
    async savePurchaseOrder(po: PurchaseOrder): Promise<void> {
        if ((this.actor as any).savePurchaseOrder) {
            await (this.actor as any).savePurchaseOrder(po);
        }
    }
    async deletePurchaseOrder(id: string): Promise<void> {
        if ((this.actor as any).deletePurchaseOrder) {
            await (this.actor as any).deletePurchaseOrder(id);
        }
    }
    async getGRNs(): Promise<Array<GRN>> {
        if ((this.actor as any).getGRNs) {
            return await (this.actor as any).getGRNs();
        }
        return [];
    }
    async saveGRN(grn: GRN): Promise<void> {
        if ((this.actor as any).saveGRN) {
            await (this.actor as any).saveGRN(grn);
        }
    }
    async receivePOItem(poId: string, qty: number, invoiceNo: string, expiryDate?: string, remarks?: string): Promise<void> {
        if ((this.actor as any).receivePOItem) {
            await (this.actor as any).receivePOItem(poId, qty, invoiceNo, expiryDate, remarks);
        }
    }
    async getPurchaseInvoices(): Promise<Array<any>> {
        if ((this.actor as any).getPurchaseInvoices) {
            return await (this.actor as any).getPurchaseInvoices();
        }
        return [];
    }
    async getPurchaseInvoiceById(id: string): Promise<any> {
        if ((this.actor as any).getPurchaseInvoiceById) {
            return await (this.actor as any).getPurchaseInvoiceById(id);
        }
        return null;
    }
    async recordPurchasePayment(invoiceId: string, paymentData: any): Promise<void> {
        if ((this.actor as any).recordPurchasePayment) {
            await (this.actor as any).recordPurchasePayment(invoiceId, paymentData);
        }
    }
    async cancelPurchaseInvoice(invoiceId: string): Promise<void> {
        if ((this.actor as any).cancelPurchaseInvoice) {
            await (this.actor as any).cancelPurchaseInvoice(invoiceId);
        }
    }
    normalizePurchaseInvoice(invoice: any): any {
        return invoice;
    }
    async migrateLegacyPurchaseInvoices(): Promise<void> {}
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
