/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BusinessInfo = string;
export interface CustomerInfo {
  'taxId' : string,
  'name' : string,
  'businessAddress' : string,
}
export interface DashboardStats {
  'allTimeTotalSales' : number,
  'todayTotalSales' : number,
  'todayInvoiceCount' : bigint,
  'allTimeInvoiceCount' : bigint,
}
export interface Invoice {
  'id' : bigint,
  'customerInfo' : CustomerInfo,
  'date' : Time,
  'businessInfo' : BusinessInfo,
  'invoiceNumber' : string,
  'totalAmount' : number,
  'products' : Array<Product>,
  'previousBalanceAtCreation'?: number,
  'advanceBalanceAtCreation'?: number,
  'currentInvoiceTotalAtCreation'?: number,
  'totalPayableAtCreation'?: number,
  'paidAmountAtCreation'?: number,
  'finalDueAtCreation'?: number,
}
export type Product = [string, bigint, bigint];
export interface Settings {
  'businessInfo' : BusinessInfo,
  'termsAndConditions' : string,
  'defaultGstRate' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getInvoiceById' : ActorMethod<[bigint], Invoice>,
  'getInvoices' : ActorMethod<[], Array<Invoice>>,
  'getSettings' : ActorMethod<[], Settings>,
  'saveInvoice' : ActorMethod<
    [BusinessInfo, CustomerInfo, Array<Product>, number],
    string
  >,
  'saveSettings' : ActorMethod<[BusinessInfo, number, string], undefined>,
  'saveRawMaterial' : ActorMethod<[string, string, string, number, number, string, number, Opt<number>, Opt<number>, Opt<string>], undefined>,
  'updateInvoice' : ActorMethod<
    [bigint, BusinessInfo, CustomerInfo, Array<Product>, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];