/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DashboardStats = IDL.Record({
  'allTimeTotalSales' : IDL.Float64,
  'todayTotalSales' : IDL.Float64,
  'todayInvoiceCount' : IDL.Nat,
  'allTimeInvoiceCount' : IDL.Nat,
});
export const CustomerInfo = IDL.Record({
  'taxId' : IDL.Text,
  'name' : IDL.Text,
  'businessAddress' : IDL.Text,
});
export const Time = IDL.Int;
export const BusinessInfo = IDL.Text;
export const Product = IDL.Tuple(IDL.Text, IDL.Nat, IDL.Int);
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'customerInfo' : CustomerInfo,
  'date' : Time,
  'businessInfo' : BusinessInfo,
  'invoiceNumber' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'products' : IDL.Vec(Product),
});
export const Settings = IDL.Record({
  'businessInfo' : BusinessInfo,
  'termsAndConditions' : IDL.Text,
  'defaultGstRate' : IDL.Float64,
});

export const idlService = IDL.Service({
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getInvoiceById' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'saveInvoice' : IDL.Func(
      [BusinessInfo, CustomerInfo, IDL.Vec(Product), IDL.Float64],
      [IDL.Text],
      [],
    ),
  'saveSettings' : IDL.Func([BusinessInfo, IDL.Float64, IDL.Text], [], []),
  'updateInvoice' : IDL.Func(
      [IDL.Nat, BusinessInfo, CustomerInfo, IDL.Vec(Product), IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DashboardStats = IDL.Record({
    'allTimeTotalSales' : IDL.Float64,
    'todayTotalSales' : IDL.Float64,
    'todayInvoiceCount' : IDL.Nat,
    'allTimeInvoiceCount' : IDL.Nat,
  });
  const CustomerInfo = IDL.Record({
    'taxId' : IDL.Text,
    'name' : IDL.Text,
    'businessAddress' : IDL.Text,
  });
  const Time = IDL.Int;
  const BusinessInfo = IDL.Text;
  const Product = IDL.Tuple(IDL.Text, IDL.Nat, IDL.Int);
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'customerInfo' : CustomerInfo,
    'date' : Time,
    'businessInfo' : BusinessInfo,
    'invoiceNumber' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'products' : IDL.Vec(Product),
  });
  const Settings = IDL.Record({
    'businessInfo' : BusinessInfo,
    'termsAndConditions' : IDL.Text,
    'defaultGstRate' : IDL.Float64,
  });
  
  return IDL.Service({
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getInvoiceById' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'saveInvoice' : IDL.Func(
        [BusinessInfo, CustomerInfo, IDL.Vec(Product), IDL.Float64],
        [IDL.Text],
        [],
      ),
    'saveSettings' : IDL.Func([BusinessInfo, IDL.Float64, IDL.Text], [], []),
    'updateInvoice' : IDL.Func(
        [IDL.Nat, BusinessInfo, CustomerInfo, IDL.Vec(Product), IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };